runtime: nodejs16

env_variables:
  DB_USER: >-
    {{{
      "name": "projects/428687573784/secrets/DB_USER/versions/latest",
      "version": "latest",
      "env": "production"
    }}}
  DB_HOST: >-
    {{{
      "name": "projects/428687573784/secrets/DB_HOST/versions/latest",
      "version": "latest",
      "env": "production"
    }}}
  DB_NAME: >-
    {{{
      "name": "projects/428687573784/secrets/DB_NAME/versions/latest",
      "version": "latest",
      "env": "production"
    }}}
  DB_PASSWORD: >-
    {{{
      "name": "projects/428687573784/secrets/DB_PASSWORD/versions/latest",
      "version": "latest",
      "env": "production"
    }}}
  DB_PORT: >-
    {{{
      "name": "projects/428687573784/secrets/DB_PORT/versions/latest",
      "version": "latest",
      "env": "production"
    }}}